require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

# Override Firebase SDK Version
$FirebaseSDKVersion = '8.4.0'

target 'Travelexic' do
  use_unimodules!
  config = use_native_modules!

  # use_react_native!(
  #   :path => config[:reactNativePath],
  #   # to enable hermes on iOS, change `false` to `true` and then install pods
  #   :hermes_enabled => false
  # )

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'TravelexicTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  
  # post_install do |installer|
  #    react_native_post_install(installer)
  #      installer.pods_project.targets.each do |target|
  #          target.build_configurations.each do |config|
  #            config.build_settings["BITCODE_GENERATION_MODE"] = "bitcode"
  #            config.build_settings["ENABLE_BITCODE"] = "YES"
  #            config.build_settings["EXCLUDED_ARCHS"] = "armv7"
  #            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
  #          end
  #      end
  #  end
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
