require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "cocoapods")

# Override Firebase SDK Version
$FirebaseSDKVersion = '8.4.0'

platform :ios, '11.0'

target 'Travelexic' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'TravelexicTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  
  post_install do |installer|
     react_native_post_install(installer)
       installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
             config.build_settings["BITCODE_GENERATION_MODE"] = "bitcode"
             config.build_settings["ENABLE_BITCODE"] = "YES"
             config.build_settings["EXCLUDED_ARCHS"] = "armv7"
             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
           end
       end
   end
end
